import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Multiple Choice Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Enter a test ID:</p>
        <input
          type="text"
          className="border border-red-100"
          placeholder="Yeah"
        ></input>
      </main>
    </>
  );
}
