import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Answer, Question } from "src/drizzle/schema";
import { api } from "~/utils/api";

export type TestContextType = {
  SelectedAnswers: { question: Question; selectedAnswers: Answer[] }[];
};

export default function TakeTest() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

type QnAType = {
  qna: { question: Question; answers: Answer[] };
};

export function QuestionSection(QnA: QnAType) {
  return (
    <>
      <Question question={QnA.qna.question} />
      <div className="flex gap-3">
        {QnA.qna.answers.map((answer) => {
          return <Answer key={answer.id} answer={answer} />;
        })}
      </div>
    </>
  );
}

export function Question(prop: { question: Question }) {
  return (
    <>
      <p>Question {prop.question.id}</p>
      <p>{prop.question.value}</p>
    </>
  );
}

export function Answer(prop: { answer: Answer; onSelect?: () => void }) {
  const [isSelected, setIsSelected] = useState(false);
  return (
    <div
      className={`border p-3 ${isSelected ? "border-green-500" : ""}`}
      onClick={() => {
        setIsSelected(!isSelected);
      }}
    >
      {prop.answer.value}
    </div>
  );
}

export function LoadingComponent() {
  return <>Loading...</>;
}
