import { redirect } from "next/navigation"
import Head from "next/head"
import Link from "next/link"
import { useState } from "react"
import { api } from "~/utils/api"
export default function LoginPage() {
  const [message, setMessage] = useState("")
  const loginUser = api.example.loginUser.useMutation({
    onSuccess: (data) => {
      if (data.user == null || data.session == null) {
        throw new Error("Login Failed");
      }
    }
  })
  function handleLogin(loginData: { email: string, password: string }) {
    loginUser.mutate(loginData)
  }
  return (
    <>
      <Head>
        <title>Login to QuickThink</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-3xl">Login to QuickThink</p>
      <form className="flex flex-col border m-3 gap-2" method="post" onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        const formData = { email: (event.target as any).email.value, password: (event.target as any).password.value }
        handleLogin(formData)
      }}>
        <input type="email" placeholder="Enter email" name="email" />
        <input type="password" placeholder="Enter password" name="password" />
        <input className="text-black border" type="submit" value="Login" />
      </form>
      <p>Don't have an account? <Link className="font-bold" href={"signup"}>Sign up</Link></p>
      {message}
    </>
  )
}
