import Head from "next/head"
import Link from "next/link";
import { useState } from "react"
import { api } from "~/utils/api";

export default function LoginPage() {
  const [message, setMessage] = useState("");
  const createUser = api.example.createUser.useMutation({
    onSuccess: () => setMessage("success")
  })

  function handleSignUp(signUpData: { email: string, password: string }) {
    createUser.mutate(signUpData)
  }

  return (
    <>
      <Head>
        <title>Sign up to QuickThink</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-3xl">Sign up to QuickThink</p>
      <form className="flex flex-col border m-3 gap-2" method="post" onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        const formData = { email: (event.target as any).email.value, password: (event.target as any).password.value }
        handleSignUp(formData)
      }}>
        <input type="email" placeholder="Enter username" name="email" />
        <input type="password" placeholder="Enter password" name="password" />
        <input className="text-black border" type="submit" value="Sign Up" />
      </form>
      <p>Already have an account? <Link className="font-bold" href={"/login"}>Sign in</Link></p>
      {message}
    </>
  )
}

